name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    # Log in to DigitalOcean Container Registry
    - name: Log in to DigitalOcean Registry
      env:
        DO_ACCESS_TOKEN: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      run: echo $DO_ACCESS_TOKEN | docker login registry.digitalocean.com -u doctl --password-stdin

    # Build the Docker image
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag registry.digitalocean.com/nuhmanregistry/hosp-connect-user-svc:latest

    # Push the Docker image to DigitalOcean Registry
    - name: Push Docker image to DigitalOcean Registry
      run: docker push registry.digitalocean.com/nuhmanregistry/hosp-connect-user-svc:latest
