name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    # Log in to Docker Hub
    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    # Build the Docker image
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag hosp-connect-user-svc:latest

    # Tag and Push the Docker image to Docker Hub
    - name: Push Docker image to Docker Hub
      run: |
        docker tag hosp-connect-user-svc:latest ${{ secrets.DOCKER_USERNAME }}/hosp-connect-user-svc:latest
        docker push ${{ secrets.DOCKER_USERNAME }}/hosp-connect-user-svc:latest

        
